#
# PySNMP MIB module SYNOLOGY-SMART-MIB (http://snmplabs.com/pysmi)
# ASN.1 source file://./SYNOLOGY-SMART-MIB.txt
# Produced by pysmi-1.1.11 at Wed Jan 10 17:46:50 2024
# On host pablo-VBox platform Linux version 6.2.0-39-generic by user pablo
# Using Python version 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
#
ObjectIdentifier, Integer, OctetString = mibBuilder.importSymbols("ASN1", "ObjectIdentifier", "Integer", "OctetString")
NamedValues, = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
ConstraintsUnion, ValueSizeConstraint, SingleValueConstraint, ValueRangeConstraint, ConstraintsIntersection = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsUnion", "ValueSizeConstraint", "SingleValueConstraint", "ValueRangeConstraint", "ConstraintsIntersection")
ObjectGroup, ModuleCompliance, NotificationGroup = mibBuilder.importSymbols("SNMPv2-CONF", "ObjectGroup", "ModuleCompliance", "NotificationGroup")
Counter64, NotificationType, enterprises, Gauge32, Unsigned32, IpAddress, iso, Integer32, MibScalar, MibTable, MibTableRow, MibTableColumn, ModuleIdentity, ObjectIdentity, Bits, Counter32, MibIdentifier, TimeTicks = mibBuilder.importSymbols("SNMPv2-SMI", "Counter64", "NotificationType", "enterprises", "Gauge32", "Unsigned32", "IpAddress", "iso", "Integer32", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "ModuleIdentity", "ObjectIdentity", "Bits", "Counter32", "MibIdentifier", "TimeTicks")
DisplayString, TextualConvention = mibBuilder.importSymbols("SNMPv2-TC", "DisplayString", "TextualConvention")
synologyDiskSMART = ModuleIdentity((1, 3, 6, 1, 4, 1, 6574, 5))
synologyDiskSMART.setRevisions(('2016-05-05 00:00',))

if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    if mibBuilder.loadTexts: synologyDiskSMART.setRevisionsDescriptions(('First draft.',))
if mibBuilder.loadTexts: synologyDiskSMART.setLastUpdated('201605050000Z')
if mibBuilder.loadTexts: synologyDiskSMART.setOrganization('www.synology.com')
if mibBuilder.loadTexts: synologyDiskSMART.setContactInfo('Synology Inc. Email: snmp@synology.com')
if mibBuilder.loadTexts: synologyDiskSMART.setDescription('Characteristics of the disk SMART information')
synology = MibIdentifier((1, 3, 6, 1, 4, 1, 6574))
diskSMARTTable = MibTable((1, 3, 6, 1, 4, 1, 6574, 5, 1), )
if mibBuilder.loadTexts: diskSMARTTable.setStatus('current')
if mibBuilder.loadTexts: diskSMARTTable.setDescription('Table of disk SMART data.')
diskSMARTEntry = MibTableRow((1, 3, 6, 1, 4, 1, 6574, 5, 1, 1), ).setIndexNames((0, "SYNOLOGY-SMART-MIB", "diskSMARTInfoIndex"))
if mibBuilder.loadTexts: diskSMARTEntry.setStatus('current')
if mibBuilder.loadTexts: diskSMARTEntry.setDescription('An entry containing a disk SMART information')
diskSMARTInfoIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 6574, 5, 1, 1, 1), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 2147483647)))
if mibBuilder.loadTexts: diskSMARTInfoIndex.setStatus('current')
if mibBuilder.loadTexts: diskSMARTInfoIndex.setDescription('SMART info index')
diskSMARTInfoDevName = MibTableColumn((1, 3, 6, 1, 4, 1, 6574, 5, 1, 1, 2), OctetString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: diskSMARTInfoDevName.setStatus('current')
if mibBuilder.loadTexts: diskSMARTInfoDevName.setDescription('SMART info device name')
diskSMARTAttrName = MibTableColumn((1, 3, 6, 1, 4, 1, 6574, 5, 1, 1, 3), OctetString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: diskSMARTAttrName.setStatus('current')
if mibBuilder.loadTexts: diskSMARTAttrName.setDescription('SMART attribute name')
diskSMARTAttrId = MibTableColumn((1, 3, 6, 1, 4, 1, 6574, 5, 1, 1, 4), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: diskSMARTAttrId.setStatus('current')
if mibBuilder.loadTexts: diskSMARTAttrId.setDescription('SMART attribute ID')
diskSMARTAttrCurrent = MibTableColumn((1, 3, 6, 1, 4, 1, 6574, 5, 1, 1, 5), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: diskSMARTAttrCurrent.setStatus('current')
if mibBuilder.loadTexts: diskSMARTAttrCurrent.setDescription('SMART attribute current value')
diskSMARTAttrWorst = MibTableColumn((1, 3, 6, 1, 4, 1, 6574, 5, 1, 1, 6), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: diskSMARTAttrWorst.setStatus('current')
if mibBuilder.loadTexts: diskSMARTAttrWorst.setDescription('SMART attribute worst value')
diskSMARTAttrThreshold = MibTableColumn((1, 3, 6, 1, 4, 1, 6574, 5, 1, 1, 7), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: diskSMARTAttrThreshold.setStatus('current')
if mibBuilder.loadTexts: diskSMARTAttrThreshold.setDescription('SMART attribute threshold value')
diskSMARTAttrRaw = MibTableColumn((1, 3, 6, 1, 4, 1, 6574, 5, 1, 1, 8), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: diskSMARTAttrRaw.setStatus('current')
if mibBuilder.loadTexts: diskSMARTAttrRaw.setDescription('SMART attribute raw value')
diskSMARTAttrStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 6574, 5, 1, 1, 9), OctetString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: diskSMARTAttrStatus.setStatus('current')
if mibBuilder.loadTexts: diskSMARTAttrStatus.setDescription('SMART attribute status')
synologyDiskSMARTConformance = MibIdentifier((1, 3, 6, 1, 4, 1, 6574, 5, 2))
synologyDiskSMARTCompliances = MibIdentifier((1, 3, 6, 1, 4, 1, 6574, 5, 2, 1))
synologyDiskSMARTGroups = MibIdentifier((1, 3, 6, 1, 4, 1, 6574, 5, 2, 2))
synologyDiskSMARTCompliance = ModuleCompliance((1, 3, 6, 1, 4, 1, 6574, 5, 2, 1, 1)).setObjects(("SYNOLOGY-SMART-MIB", "synologyDiskSMARTGroup"))

if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    synologyDiskSMARTCompliance = synologyDiskSMARTCompliance.setStatus('current')
if mibBuilder.loadTexts: synologyDiskSMARTCompliance.setDescription('The compliance statement for storage IO entities which implement the SYNOLOGY SMART MIB.')
synologyDiskSMARTGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 6574, 5, 2, 2, 1)).setObjects(("SYNOLOGY-SMART-MIB", "diskSMARTInfoDevName"), ("SYNOLOGY-SMART-MIB", "diskSMARTAttrName"), ("SYNOLOGY-SMART-MIB", "diskSMARTAttrId"), ("SYNOLOGY-SMART-MIB", "diskSMARTAttrCurrent"), ("SYNOLOGY-SMART-MIB", "diskSMARTAttrWorst"), ("SYNOLOGY-SMART-MIB", "diskSMARTAttrThreshold"), ("SYNOLOGY-SMART-MIB", "diskSMARTAttrRaw"), ("SYNOLOGY-SMART-MIB", "diskSMARTAttrStatus"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    synologyDiskSMARTGroup = synologyDiskSMARTGroup.setStatus('current')
if mibBuilder.loadTexts: synologyDiskSMARTGroup.setDescription('A collection of objects providing basic information of an synology disk SMART entity.')
mibBuilder.exportSymbols("SYNOLOGY-SMART-MIB", synologyDiskSMARTGroups=synologyDiskSMARTGroups, synologyDiskSMARTGroup=synologyDiskSMARTGroup, diskSMARTInfoIndex=diskSMARTInfoIndex, PYSNMP_MODULE_ID=synologyDiskSMART, synologyDiskSMARTCompliance=synologyDiskSMARTCompliance, synologyDiskSMARTConformance=synologyDiskSMARTConformance, diskSMARTAttrCurrent=diskSMARTAttrCurrent, diskSMARTEntry=diskSMARTEntry, synologyDiskSMARTCompliances=synologyDiskSMARTCompliances, diskSMARTInfoDevName=diskSMARTInfoDevName, synology=synology, synologyDiskSMART=synologyDiskSMART, diskSMARTAttrStatus=diskSMARTAttrStatus, diskSMARTAttrWorst=diskSMARTAttrWorst, diskSMARTAttrThreshold=diskSMARTAttrThreshold, diskSMARTTable=diskSMARTTable, diskSMARTAttrName=diskSMARTAttrName, diskSMARTAttrRaw=diskSMARTAttrRaw, diskSMARTAttrId=diskSMARTAttrId)
